name: Build MysteryGiftTool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup NuGet
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      # Step 3: Restore NuGet packages for the solution
      - name: Restore NuGet packages
        run: nuget restore MysteryGiftTool.sln

      # Step 4: Build PKHeX.Core first
      - name: Build PKHeX.Core
        run: msbuild PKHeX/PKHeX.Core.csproj /p:Configuration=Release /p:Platform="Any CPU"

      # Step 5: Build MysteryGiftTool Debug
      - name: Build MysteryGiftTool Debug
        run: msbuild MysteryGiftTool/MysteryGiftTool.csproj /p:Configuration=Debug /p:Platform="Any CPU"

      # Step 6: Build MysteryGiftTool Release
      - name: Build MysteryGiftTool Release
        run: msbuild MysteryGiftTool/MysteryGiftTool.csproj /p:Configuration=Release /p:Platform="Any CPU"

      # Step 7: Upload Release build artifact
      - name: Upload Release Build
        uses: actions/upload-artifact@v3
        with:
          name: MysteryGiftTool-Release
          path: MysteryGiftTool/MysteryGiftTool/bin/Release/
