name: Build MysteryGiftTool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup NuGet
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      # Step 3: Restore NuGet packages for the solution
      - name: Restore NuGet packages
        run: nuget restore MysteryGiftTool.sln

      # Step 4: Build Debug
      - name: Build Debug
        run: msbuild MysteryGiftTool.sln /p:Configuration=Debug /p:Platform="Any CPU"
        working-directory: MysteryGiftTool

      # Step 5: Build Release
      - name: Build Release
        run: msbuild MysteryGiftTool.sln /p:Configuration=Release /p:Platform="Any CPU"
        working-directory: MysteryGiftTool

      # Step 6: Upload Release build artifact
      - name: Upload Release Build
        uses: actions/upload-artifact@v3
        with:
          name: MysteryGiftTool-Release
          path: MysteryGiftTool/bin/Release/
